export enum ECustomerContextConsts {
	SET_TOGGLE_IS_VISIBLE_ONE_ITEM_AND_INIT_EVERYTHING_ELSE = 'SET_TOGGLE_IS_VISIBLE_ONE_ITEM_AND_INIT_EVERYTHING_ELSE',
	SET_CART = 'SET_CART',
	ADD_TO_CART = 'ADD_TO_CART',
	UPDATE_ONE_PRODUCT_ON_CART = 'UPDATE_ONE_PRODUCT_ON_CART',
	UPDATE_MANY_PRODUCT_ON_CART = 'UPDATE_MANY_PRODUCT_ON_CART',
	DELETE_ONE_PRODUCT_ON_CART = 'DELETE_ONE_PRODUCT_ON_CART'
}
