export enum ECustomerContextConsts {
	TOGGLE_IS_ONE_ITEM_VISIBLE = 'TOGGLE_IS_ONE_ITEM_VISIBLE',
	SET_IS_ONE_ITEM_VISIBLE = 'SET_IS_ONE_ITEM_VISIBLE',
	SET_CART = 'SET_CART',
	ADD_TO_CART = 'ADD_TO_CART',
	UPDATE_ONE_PRODUCT_ON_CART = 'UPDATE_ONE_PRODUCT_ON_CART',
	UPDATE_MANY_PRODUCT_ON_CART = 'UPDATE_MANY_PRODUCT_ON_CART',
	DELETE_ONE_PRODUCT_ON_CART = 'DELETE_ONE_PRODUCT_ON_CART',
}
